-- 建立測試資料表
CREATE TABLE TestMessages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Message NVARCHAR(MAX),
    CreatedAt DATETIME DEFAULT GETDATE()
);

-- 啟用 Service Broker (SQL Dependency 需要)
ALTER DATABASE SignalR SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;

-- 授予權限
GRANT CREATE SUBSCRIPTION TO [sa];
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [sa];
